### ISSUE TITLE
Many recipes work. But there are recipes that don't work at all, and there are recipes that have the wrong number.

### ISSUE THREAD

**Issue by EndlessLegends** [DidlDimpfe/Automatic-Crafting-Table-Plugin#1]
- server version
papermc 1.19.4 - build #524
- plugins
AngelChest, AutomaticCraftingTable, BetterTridents, BlockProt, Brewery, ChestSort, Chunky, ChunkyBorder, CMI, *CMIEInjector, CMILib, CommandPanels, CoreProtect, Elevator, EvenMoreFish, FastAsyncWorldEdit, Freeze, *KAKC, LuckPerms, PL-Hide, Pl3xMap, PlaceholderAPI, ProtocolLib, Quests, ShiftHotkey, Shopkeepers, Vault, WebStats, YamipaPlugin

- plugin version.
AutomaticCraftingTable-1.2.0

These are plugins that may be added or removed in the future. for testing.

----------------------------------------------

/papi parse me %automaticcraftingtableUsedRecipes%

{ItemStack(CRIMSON_PLANKS x 4}, etc...

but, not work...

----------------------------------------------

hello, guys.

When I first installed and ran this plugin, I tested making oak_log oak_planks. It didn't work so I thought this plugin was either bad or not running. But items from other recipes work really well. Therefore, it was a bug that only applied to a few items. Not all items were recipe-following. There are things that go well. Not all recipes could be tested. There is no time. [But I've found that if there's no shape, and there are more than 2 outputs, it's almost always wrong.]

----------------------------------------------
For example..)
*_planks * 2 (| shaped) => stick * 1 (original. stick * 4)
*_log *1 => It doesn't work (original. *_planks *4)
iron_ingot *1 => iron_nugget * 1 (original. iron_nugget * 9)
----------------------------------------------

P.s. I am not a native speaker. I had help from a translator.

I love this great idea plugin. It would be even nicer if everything worked fine.

Thank you.

**Comment by DidlDimpfe** [comment]
Hey, thank you for this bug report! I fixed it and will update the recource with the new Version 1.2.1. Download it and it works fine. If you find more bugs please report it here!
