### ISSUE TITLE
Too many automatic synthesis stations will make the server stuck.

### ISSUE THREAD

**Issue by AngelLuoLi** [DidlDimpfe/Automatic-Crafting-Table-Plugin#10]
I found that there was also a jam when the server was not online. After looking for the reason, I found that it was caused by the AutomaticCraftingTable plug-in.

**Comment by DidlDimpfe** [comment]
Hello, how many crafting tables were you using?

**Comment by AngelLuoLi** [comment]
> Hello, how many crafting tables were you using?

There are more than 500 servers, and that area will also get stuck when it is not loaded.
