### ISSUE TITLE
This is a very creative plug-in, but I have encountered some problems in use. I hope you can help me solve them.

### ISSUE THREAD

**Issue by AngelLuoLi** [DidlDimpfe/Automatic-Crafting-Table-Plugin#11]
After the server is restarted, the synthesizer cannot be opened, and it will become a common workbench after being destroyed.

**Comment by AngelLuoLi** [comment]
I also found that too many automatic synthesizers can cause the server to get stuck. Even if there is no one in the server, mspt will rise. After checking with spark, it is found that the plug-in of AutomaticCraftingTable takes up a lot of space.

**Comment by AngelLuoLi** [comment]
> After the server is restarted, the synthesizer cannot be opened, and it will become a common workbench after being destroyed.

Appears when separate-from-other-crafting-tables is enabled.

**Comment by DidlDimpfe** [comment]
"separate-from-other-crafting-tables" fixed in 1.4.2. Contact me if you find any more issues!
