### ISSUE TITLE
Many NBT tags get deleted inside the Automatic Crafting Table Recipe

### ISSUE THREAD

**Issue by nyapommy** [DidlDimpfe/Automatic-Crafting-Table-Plugin#12]
If you place an item that has custom attribute modifiers, the Unbreakable tag, custom potion effects, custom potion colors, etc, it loses all that data.

This tampers severely with my intentions with the plugin, and I'd really appreciate if it is fixed. Thank you.

I'm using Pufferfish-Purpur 1.17.1.

![image](https://github.com/DidlDimpfe/Automatic-Crafting-Table-Plugin/assets/79335163/7c90abfa-77fc-4425-b015-3676f587bc8d)

**Comment by DidlDimpfe** [comment]
That's fixed, but I won't upload it until I fix the problem with "seperate-from-other-crafting-tables", which I'm not doing anymore today.
