### ISSUE TITLE
Custom recipes that use multiple of the same unstackable item don't work correctly

### ISSUE THREAD

**Issue by nyapommy** [DidlDimpfe/Automatic-Crafting-Table-Plugin#16]
When autocrafting recipes that use multiple of the same unstackable item in them, the Automatic Crafting Recipe only requires one of that unstackable item to succesfully craft the recipe.

For example, I'm trying to craft this custom recipe in the ACT.
(All these items are leather horse armors with custom NBT values, the unstackable item with multiple appearances in this case is the cyan gem)
![image](https://github.com/DidlDimpfe/Automatic-Crafting-Table-Plugin/assets/79335163/9e2bb409-e310-4dd0-996b-333d5e328c84)

The Automatic Crafting Table only requires one of those cyan gems instead of four to craft the recipe.
![image](https://github.com/DidlDimpfe/Automatic-Crafting-Table-Plugin/assets/79335163/77fd7907-6ab5-4163-a88f-b97c049381ce)
(The ACT considers this to be enough to craft the recipe)

This doesn't only happen with items with custom NBT values, it also happens with regular unstackable items, like netherite swords or boats.

It would be greatly appreciated if you fix this issue, thank you :3

I'm using Purpur 1.20.1

**Comment by DidlDimpfe** [comment]
Can you test this in the new Version? (Connect multiple hoppers into the crafting table, because 1 hopper can't hold all items)

**Comment by nyapommy** [comment]
> Can you test this in the new Version? (Connect multiple hoppers into the crafting table, because 1 hopper can't hold all items)

I tested it and it works perfectly now
