### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by Aides123** [DidlDimpfe/Automatic-Crafting-Table-Plugin#2]
Hi! I found way to duplication items.
Can I report here?

**Comment by DidlDimpfe** [comment]
Yes, sure!

**Comment by Aides123** [comment]
> Yes, sure!

Well then:
- You have to create something like this and the lower HOPPER has to be all filled up. If we do this then items will fall out and duplicate.
![2023-06-26_10 44 08](https://github.com/DidlDimpfe/Automatic-Crafting-Table-Plugin/assets/23367220/f71db363-25aa-47b8-a308-599d16d08de2)

**Comment by Aides123** [comment]
Hi! When can repairs be expected? ^^

**Comment by DidlDimpfe** [comment]
Wich items did you put in the lower hopper? I tested it and it worked fine.

**Comment by Aides123** [comment]
I Will test on the server without additional plug-ins.

**Comment by Aides123** [comment]
I have now checked on the server without plug-ins and the problem apparently comes from me. Because it is not possible to copy items anymore.

**Comment by DidlDimpfe** [comment]
Okay
