### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Aides123** [DidlDimpfe/Automatic-Crafting-Table-Plugin#3]
Hi! 
I downloaded the latest version of the plugin and uploaded it to the server. After restarting, errors appeared.
PufferFish: #15 version 1.20.1

https://pastebin.com/nWJXhLcf

**Comment by DidlDimpfe** [comment]
Did it work before restarting?

**Comment by Aides123** [comment]
> Did it work before restarting?

I have now checked on the server without plug-ins and the problem continues

**Comment by DidlDimpfe** [comment]
I tested it with the same initial position as you: PufferFish: #15 version 1.20.1. It worked for me. Do you have anymore information?

**Comment by Aides123** [comment]
on the latest version of pufferfish no longer has the error .-.
