### ISSUE TITLE
Proposal - New workbench

### ISSUE THREAD

**Issue by Aides123** [DidlDimpfe/Automatic-Crafting-Table-Plugin#4]
Hey! I propose to add a NEW workbench that will automatically produce items.
That is, instead of swapping regular workbenches you will need to get a CUSTOM workbench to produce recipes automatically.

**Comment by DidlDimpfe** [comment]
I cannot make a new texture, but I can make it so it has a different name. Should I do that (only if the config says it wants that)?

**Comment by Aides123** [comment]
"Should I do that (only if the config says it wants that)?" Yes, it would be great

**Comment by DidlDimpfe** [comment]
I am currenlty on vacation. When I come back I do it.
