### ISSUE TITLE
An error occurred while decomposing the mucus block.

### ISSUE THREAD

**Issue by AngelLuoLi** [DidlDimpfe/Automatic-Crafting-Table-Plugin#5]
When the mucus block is decomposed, only one mucus ball can be obtained in the end. Correct should be nine.

**Comment by AngelLuoLi** [comment]
So is the same glass plate.

**Comment by AngelLuoLi** [comment]
I probably understand how the plug-in works. You can create a composite table configuration file. Let's configure it ourselves. This also enables you to customize the composition table.

**Comment by DidlDimpfe** [comment]
I tried it and I got 9 mucus balls. What version do you have?

**Comment by AngelLuoLi** [comment]
Single decomposition is normal. If you put in 64 mucus blocks, it will have problems.

**Comment by DidlDimpfe** [comment]
Fixed on 1.4.1 :D
