### ISSUE TITLE
In version 1.4.0, the Crafting-Table-UI-Needpermission is invalid, and players without permission can still use it after opening it.

### ISSUE THREAD

**Issue by AngelLuoLi** [DidlDimpfe/Automatic-Crafting-Table-Plugin#6]
In version 1.4.0, the Crafting-Table-UI-Needpermission is invalid, and players without permission can still use it after opening it.

**Comment by DidlDimpfe** [comment]
Yes, I thought it would not be needed anymore. Should I add it back?

**Comment by AngelLuoLi** [comment]
Well, there are many ways to play with permission. . You can also cooperate with separate-from-other-crafting-tables to realize that you can use it directly if you have permission. Those who have no authority can only buy a special synthesis station to use it.
