### ISSUE TITLE
[Server thread/WARN]: ... usage of System.out/err.print.

### ISSUE THREAD

**Issue by misha447** [DidlDimpfe/Automatic-Crafting-Table-Plugin#8]
Hello, i got this server warning in the logs while turning on a paper 1.20.1 server.
> [Server thread/WARN]: Nag author(s): '[Phil]' of 'AutomaticCraftingTable v1.4.0' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).

**Comment by DidlDimpfe** [comment]
Changed on 1.4.1 :D
