### ISSUE TITLE
Firework Rockets with Flight Duration 2 and 3 recipe not working

### ISSUE THREAD

**Issue by sdosker** [DidlDimpfe/Automatic-Crafting-Table-Plugin#9]
As title says, Flight Duration 2 and 3 Firework Rockets recipe isn't working even tho it's a shapeless recipe

Flight Duration 1 rockets works just fine, but adding more gunpowder to the recipe stops the crafting

**Comment by DidlDimpfe** [comment]
Fixed on 1.4.1 :D
